# Generated by Django 4.1.1 on 2024-03-07 14:23

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=userauth.models.user_director_path),
        ),
    ]
